moves/urls.py
from django.urls import path

from . import views


app_name = "moves"

urlpatterns = [
    path("", views.move_list, name="list"),
    path("<int:move_id>", views.move_detail, name="detail"),
    path("<int:move_id>/print", views.move_detail_print, name="print"),
]

partners/api/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path("", views.ListCreatePartner.as_view(), name="partner-list"),
    path(
        "<int:pk>/",
        views.RetrieveUpdateDestroyPartner.as_view(),
        name="partner-detail"
    ),
]

partners/urls.py
from django.urls import path
from . import views


app_name = "partners"

urlcustomers = []
urlproviders = []

urlpatterns = [
    # Socios de Negocio / Proveedores
    path("", views.PartnerList.as_view(), name="partner-list"),
    path("<int:pk>/", views.PartnerDetail.as_view(), name="partner-detail"),
    path("providers/", views.ProviderList.as_view(), name="provider-list"),
    path("customers/", views.CustomerList.as_view(), name="customer-list"),
    # Socios de Negocio / Clientes
    # Socios de Negocio / Proveedores / Contactos
    # path("providers/<int:pk>/", views.ProviderDetail.as_view(), name="detail"),
]

partners/models.py
from django.contrib.contenttypes.fields import GenericRelation
from django.contrib.postgres import fields
from django.db import models
from django.utils.translation import gettext_lazy as _

from contacts.models import Contact
from universal.models import Country
from sunqu.behaviors import Timestampable


class Partner(Timestampable, models.Model):
    """ Socios de Negocio """
    # RUC / DNI
    fiscal_number = models.CharField(_("fiscal number"), max_length=25)
    # Razón social anterior
    old_business_name = models.CharField(
        _("old bussines name"),
        blank=True,
        default="",
        max_length=255
    )
    # Razón social
    business_name = models.CharField(
        _("business name"),
        max_length=255
    )
    # Nombre comercial
    tradename = models.CharField(
        _("tradename"),
        blank=True,
        default="",
        max_length=255
    )
    # Alias
    alias = models.CharField(
        _("alias"),
        blank=True,
        default="",
        max_length=150
    )
    # Alias corto
    short_alias = models.CharField(
        _("short alias"),
        blank=True,
        default="",
        max_length=20
    )
    # Dirección Fiscal
    fiscal_address = models.TextField(
        _("fiscal address"),
        blank=True,
        default=""
    )
    # Dirección segunda línea
    address_second_line = models.CharField(
        _("address second line"),
        blank=True,
        default="",
        max_length=254
    )
    # Localización
    location = models.CharField(
        _("location"),
        blank=True,
        default="",
        help_text=_("District, City, State"),
        max_length=254
    )
    # Código de Ubicación Geográfica
    # https://www.reniec.gob.pe/Adherentes/jsp/ListaUbigeos.jsp
    ubigeo = models.CharField(
        _("ubigeo code"),
        blank=True,
        default="",
        help_text="https://www.reniec.gob.pe/Adherentes/jsp/ListaUbigeos.jsp",
        max_length=6
    )
    # País
    country = models.ForeignKey(
        Country, on_delete=models.PROTECT, verbose_name=_("country"))
    # ¿Está activo?
    is_active = models.BooleanField(_("is active"), default=True)
    # ¿Es una compañía?
    is_company = models.BooleanField(
        _("is company"),
        default=True,
        help_text=_("mark if it's a company, blank if is a person.")
    )
    # ¿Es un cliente?
    is_customer = models.BooleanField(_("is customer"))
    # ¿Es un proveedor?
    is_vendor = models.BooleanField(_("is provider"))
    # ¿Es agente de retencion?
    is_retention_agent = models.BooleanField(
        _("is_retention_agent"),
        default=False
    )
    # Categorías / Rubros
    categories = fields.ArrayField(
        models.CharField(blank=True, max_length=150),
        blank=True,
        null=True,
        verbose_name=_("categories")
    )
    # Email
    email = models.EmailField(_("email"), blank=True, default="")
    # Teléfonos
    phones = fields.ArrayField(
        models.CharField(max_length=150, blank=True, default=""),
        blank=True,
        null=True,
        verbose_name=_("phones")
    )
    # Sitio web
    web_site = models.TextField(_("web site"), blank=True, default="")
    # Fecha de baja
    deactivation_date = models.DateTimeField(
        _("deactivation date"),
        blank=True,
        null=True
    )
    # Contactos
    directory = models.ManyToManyField(
        Contact,
        blank=True,
        related_name="partners"
    )
    # Bancos
    banks = models.ManyToManyField(
        "self",
        symmetrical=False,
        through="Account"
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["fiscal_number"], name="unique_fiscal_number"
            ),
            models.UniqueConstraint(
                fields=["business_name"], name="unique_business_name"
            )
        ]
        ordering = ["business_name"]

    def __str__(self):
        return f"{self.business_name}"


class Account(Timestampable, models.Model):
    """ Cuentas bancarias """
    # socio de negocio
    partner = models.ForeignKey(
        Partner,
        on_delete=models.CASCADE,
        related_name="accounts",
        verbose_name=_("partner")
    )
    # descripción / nombre
    description = models.CharField(
        _("description"),
        max_length=255
    )
    # número de cuenta
    number = models.CharField(
        _("account number"),
        max_length=50
    )
    # número de cuenta interbancario
    interbank_code = models.CharField(
        _("interbank code"),
        blank=True,
        help_text=_("CCI"),
        max_length=50,
        null=True
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["number"], name="unique_account_number"
            ),
            models.UniqueConstraint(
                fields=["interbank_code"], name="unique_interbank_code"
            )
        ]

    def __str__(self):
        return f"{self.number}"

partners/api/views.py
from rest_framework import generics

from ..models import Partner
from .serializers import PartnerSerializer


class ListCreatePartner(generics.ListCreateAPIView):
	queryset = Partner.objects.all()
	serializer_class = PartnerSerializer


class RetrieveUpdateDestroyPartner(generics.RetrieveUpdateDestroyAPIView):
	queryset = Partner.objects.all()
	serializer_class = PartnerSerializer

partners/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views.generic import (
    ListView,
    DetailView,
    UpdateView,
    CreateView,
    DeleteView
)

from .models import Partner
from . import utils


class PartnerList(LoginRequiredMixin, ListView):
    model = Partner


class CustomerList(LoginRequiredMixin, ListView):
    model = Partner
    queryset = Partner.objects.filter(is_customer=True)
    template_name = "partners/customer_list.html"


class ProviderList(LoginRequiredMixin, ListView):
    model = Partner
    queryset = Partner.objects.filter(is_vendor=True)
    template_name = "partners/provider_list.html"


class PartnerDetail(DetailView):
    model = Partner

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["directory"] = self.object.directory.all()
        context["accounts"] = self.object.accounts.order_by("description")
        return context

partners/templates/partners/customer_base.html
{% extends "layouts/sidebar_main.html" %}
{% load static %}


{% comment %}
-------------------------------------------------------------------------------
TITULO DE VENTANA
-------------------------------------------------------------------------------
{% endcomment %}
{% block title %}Limitless | Clientes{% endblock title %}


{% comment %}
-------------------------------------------------------------------------------
NAVEGACION LATERAL
-------------------------------------------------------------------------------
{% endcomment %}
{% block navigation %}
{% include "partners/navigation.html" %}
{% endblock navigation %}


{% comment %}
-------------------------------------------------------------------------------
TITULO DE PAGINA
-------------------------------------------------------------------------------
{% endcomment %}
{% block page_icon %}<i class="fas fa-handshake mr-2"></i>{% endblock page_icon %}
{% block page_title %}Clientes{% endblock page_title %}


{% comment %}
-------------------------------------------------------------------------------
BREADCRUMBS
-------------------------------------------------------------------------------
{% endcomment %}
{% block breadcrumb %}
    <a href="#" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Inicio</a>
    <a href="{% url 'partners:partner-list' %}" class="breadcrumb-item">Socios de Negocio</a>
{% endblock breadcrumb %}

partners/templates/partners/customer_list.html
{% extends "partners/customer_base.html" %}
{% load static %}


{% comment %}
-------------------------------------------------------------------------------
JS Files
-------------------------------------------------------------------------------
{% endcomment %}
{% block before_app_js %}
<script src="{% static 'js/plugins/tables/datatables/datatables.min.js' %}"></script>
<script src="{% static 'js/plugins/tables/datatables/extensions/responsive.min.js' %}"></script>
<script src="{% static 'js/plugins/forms/selects/select2.min.js' %}"></script>
{% endblock before_app_js %}
{% block after_app_js %}
<script src="{% static 'js/config/datatables/datatable_responsive.js' %}"></script>
<script src="{% static 'partners/js/partners.js' %}"></script>
{% endblock after_app_js %}


{% comment %}
-------------------------------------------------------------------------------
TITULO SECUNDARIO
-------------------------------------------------------------------------------
{% endcomment %}
{% block page_secondary_title %}<span class="font-weight-light text-grey-600"> / Lista</span>{% endblock %}


{% comment %}
-------------------------------------------------------------------------------
SUBTITULO DE PAGINA
-------------------------------------------------------------------------------
{% endcomment %}
{% block page_subtitle %}{% endblock page_subtitle %}
{% block header_elements %}{% endblock header_elements %}


{% comment %}
-------------------------------------------------------------------------------
BREADCRUMB
-------------------------------------------------------------------------------
{% endcomment %}
{% block breadcrumb %}
    {{ block.super }}
    <a class="breadcrumb-item">Clientes</a>
    <span class="breadcrumb-item active">Lista</span>
{% endblock breadcrumb %}

{% comment %} BREADCRUMB ELEMENTS {% endcomment %}
{% block breadcrumb_elements %}{% endblock breadcrumb_elements %}


{% comment %}
-------------------------------------------------------------------------------
CONTENT
-------------------------------------------------------------------------------
{% endcomment %}
{% block content %}
<div class="card">
    <div class="card-header bg-light header-elements-inline">
        <h5 class="card-title">Directorio de Clientes</h5>
        <div class="header-elements">
            <div class="list-icons">
                <a target="_blank"  href="#" class="btn btn-sm btn-light ml-3"><i class="icon-database-add mr-2"></i> Registrar</a>
            </div>
        </div>
    </div>

    <table class="table table-xs customer-datatable">
        <thead>
            <tr>
                <th></th>
                <th>RUC</th>
                <th>Razón Social</th>
                <th>Activo</th>
                <th><span class="text-muted"><i class="icon-cog3"></i></span></th>
            </tr>
        </thead>
        <tbody>
            {% for partner in object_list %}
            <tr>
                <td></td>
                <td><a href="{% url 'partners:partner-detail' partner.pk %}">{{ partner.fiscal_number }}</a></td>
                <td>{{ partner.business_name }}</td>
                <td>
                    <span hidden>{{ partner.is_active }}</span>
                    {% if partner.is_active %}
                    <span class="text-success"><i class="icon-checkmark3"></i></span>
                    {% else %}
                    <span class="text-danger"><i class="icon-cross2"></i></span>
                    {% endif %}
                </td>
                <td>-</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}


{% comment %}
-------------------------------------------------------------------------------
FOOTER
-------------------------------------------------------------------------------
{% endcomment %}

partners/templates/partners/navigation.html
<li class="nav-item-header">
    <div class="text-uppercase font-size-xs line-height-xs">Socios De Negocio</div> <i class="icon-menu" title="Main"></i>
</li>
<li class="nav-item">
    <a href="{% url 'partners:partner-list' %}" class="nav-link ">
        <i class="fas fa-handshake"></i>
        <span>Socios de Negocio</span>
    </a>
</li>
<li class="nav-item">
    <a href="{% url 'partners:customer-list' %}" class="nav-link ">
        <i class="fas fa-user-tie"></i>
        <span>Clientes</span>
    </a>
</li>
<li class="nav-item">
    <a href="{% url 'partners:provider-list' %}" class="nav-link ">
        <i class="fas fa-user-secret"></i>
        <span>Proveedores</span>
    </a>
</li>

partners/templates/partners/partner_base.html
{% extends "layouts/sidebar_main.html" %}
{% load static %}


{% comment %}
-------------------------------------------------------------------------------
TITULO DE VENTANA
-------------------------------------------------------------------------------
{% endcomment %}
{% block title %}Limitless | Socios de Negocio{% endblock title %}


{% comment %}
-------------------------------------------------------------------------------
NAVEGACION LATERAL
-------------------------------------------------------------------------------
{% endcomment %}
{% block navigation %}
{% include "partners/navigation.html" %}
{% endblock navigation %}


{% comment %}
-------------------------------------------------------------------------------
TITULO DE PAGINA
-------------------------------------------------------------------------------
{% endcomment %}
{% block page_icon %}<i class="fas fa-handshake mr-2"></i>{% endblock page_icon %}
{% block page_title %}Socios de Negocio{% endblock page_title %}


{% comment %}
-------------------------------------------------------------------------------
BREADCRUMBS
-------------------------------------------------------------------------------
{% endcomment %}
{% block breadcrumb %}
    <a href="#" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Inicio</a>
    <a href="{% url 'partners:partner-list' %}" class="breadcrumb-item">Socios de Negocio</a>
{% endblock breadcrumb %}

partners/templates/partners/partner_list.html
{% extends "partners/partner_base.html" %}
{% load static %}


{% comment %}
-------------------------------------------------------------------------------
JS Files
-------------------------------------------------------------------------------
{% endcomment %}
{% block before_app_js %}
<script src="{% static 'js/plugins/tables/datatables/datatables.min.js' %}"></script>
<script src="{% static 'js/plugins/tables/datatables/extensions/responsive.min.js' %}"></script>
<script src="{% static 'js/plugins/forms/selects/select2.min.js' %}"></script>
{% endblock before_app_js %}
{% block after_app_js %}
<script src="{% static 'js/config/datatables/datatable_responsive.js' %}"></script>
<script src="{% static 'partners/js/partners.js' %}"></script>
{% endblock after_app_js %}


{% comment %}
-------------------------------------------------------------------------------
TITULO SECUNDARIO
-------------------------------------------------------------------------------
{% endcomment %}
{% block page_secondary_title %}<span class="font-weight-light text-grey-600"> / Lista</span>{% endblock %}


{% comment %}
-------------------------------------------------------------------------------
SUBTITULO DE PAGINA
-------------------------------------------------------------------------------
{% endcomment %}
{% block page_subtitle %}{% endblock page_subtitle %}
{% block header_elements %}{% endblock header_elements %}


{% comment %}
-------------------------------------------------------------------------------
BREADCRUMB
-------------------------------------------------------------------------------
{% endcomment %}
{% block breadcrumb %}
    {{ block.super }}
    <span class="breadcrumb-item active">Lista</span>
{% endblock breadcrumb %}

{% comment %} BREADCRUMB ELEMENTS {% endcomment %}
{% block breadcrumb_elements %}{% endblock breadcrumb_elements %}


{% comment %}
-------------------------------------------------------------------------------
CONTENT
-------------------------------------------------------------------------------
{% endcomment %}
{% block content %}
<div class="card">
    <div class="card-header bg-light header-elements-inline">
        <h5 class="card-title">Directorio de Socios</h5>
        <div class="header-elements">
            <div class="list-icons">
                <a target="_blank"  href="{% url 'admin:partners_partner_add' %}" class="btn btn-sm btn-light ml-3"><i class="icon-database-add mr-2"></i>Registrar</a>
            </div>
        </div>
    </div>

    <table class="table table-xs partner-datatable">
        <thead>
            <tr>
                <th></th>
                <th>RUC</th>
                <th>Socio</th>
                <th>Cliente</th>
                <th>Proveedor</th>
                <th>Activo</th>
                <th><span class="text-muted"><i class="icon-cog3"></i></span></th>
            </tr>
        </thead>
        <tbody>
            {% for partner in object_list %}
            <tr>
                <td></td>
                <td><a href="{% url 'partners:partner-detail' partner.pk %}">{{ partner.fiscal_number }}</a></td>
                <td>{{ partner.business_name }}</td>
                <td>
                    <span hidden>{{ partner.is_customer }}</span>
                    {% if partner.is_customer %}
                    <span class="text-success"><i class="icon-checkmark3"></i></span>
                    {% else %}
                    <span class="text-danger"><i class="icon-cross2"></i></span>
                    {% endif %}
                </td>
                <td>
                    <span hidden>{{ partner.is_vendor }}</span>
                    {% if partner.is_vendor %}
                    <span class="text-success"><i class="icon-checkmark3"></i></span>
                    {% else %}
                    <span class="text-danger"><i class="icon-cross2"></i></span>
                    {% endif %}
                </td>
                <td>
                    <span hidden>{{ partner.is_active }}</span>
                    {% if partner.is_active %}
                    <span class="text-success"><i class="icon-checkmark3"></i></span>
                    {% else %}
                    <span class="text-danger"><i class="icon-cross2"></i></span>
                    {% endif %}
                </td>
                <td>-</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}


{% comment %}
-------------------------------------------------------------------------------
FOOTER
-------------------------------------------------------------------------------
{% endcomment %}

partners/templates/partners/provider_base.html
{% extends "layouts/sidebar_main.html" %}
{% load static %}


{% comment %}
-------------------------------------------------------------------------------
TITULO DE VENTANA
-------------------------------------------------------------------------------
{% endcomment %}
{% block title %}Limitless | Proveedores{% endblock title %}


{% comment %}
-------------------------------------------------------------------------------
NAVEGACION LATERAL
-------------------------------------------------------------------------------
{% endcomment %}
{% block navigation %}
{% include "partners/navigation.html" %}
{% endblock navigation %}


{% comment %}
-------------------------------------------------------------------------------
TITULO DE PAGINA
-------------------------------------------------------------------------------
{% endcomment %}
{% block page_icon %}<i class="fas fa-handshake mr-2"></i>{% endblock page_icon %}
{% block page_title %}Proveedores{% endblock page_title %}


{% comment %}
-------------------------------------------------------------------------------
BREADCRUMBS
-------------------------------------------------------------------------------
{% endcomment %}
{% block breadcrumb %}
    <a href="#" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Inicio</a>
    <a href="{% url 'partners:partner-list' %}" class="breadcrumb-item">Socios de Negocio</a>
{% endblock breadcrumb %}

partners/templates/partners/provider_detail.html
{% extends 'partners/provider_base.html' %}

{% block page_title %}
<div class="page-title d-flex">
    <h5>
        <i class="icon-user-tie mr-2"></i> <span class="font-weight-semibold">Socios de Negocio</span>
        <small class="text-muted">
        {% if object.alias == ''  %}
            {{ object.business_name }}
        {% else %}
            {{ object.alias }}
        {% endif %}
        </small>
    </h5>
    <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
</div>
{% endblock page_title %}

{% block breadcrumb %}
<a href="#" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Dashboard</a>
<a href="{% url 'partners:provider-list' %}" class="breadcrumb-item">Socios de Negocio</a>
<span class="breadcrumb-item active">{{ object.identity_number }}</span>
{% endblock breadcrumb %}


{% block content %}
    {% for contact in contacts %}
        <section>
            <span class="h6 font-weight-semibold">{{ contact }}</span><br>
            <span class="text-info">{{ contact.title }}</span><br>
            <small class="text-info">{{ contact.branch_office }}</small><br>
            <strong>tel:</strong><br>
            {{ contact.phones|join:" // " }}
            <br>
            <strong>email:</strong>
            <a href="mailto:{{ contact.email }}">{{ contact.email }}</a>
        </section>
        <hr>
    {% endfor %}
        
{% endblock content %}
    

partners/templates/partners/provider_list.html
{% extends "partners/provider_base.html" %}
{% load static %}


{% comment %}
-------------------------------------------------------------------------------
JS Files
-------------------------------------------------------------------------------
{% endcomment %}
{% block before_app_js %}
<script src="{% static 'js/plugins/tables/datatables/datatables.min.js' %}"></script>
<script src="{% static 'js/plugins/tables/datatables/extensions/responsive.min.js' %}"></script>
<script src="{% static 'js/plugins/forms/selects/select2.min.js' %}"></script>
{% endblock before_app_js %}
{% block after_app_js %}
<script src="{% static 'js/config/datatables/datatable_responsive.js' %}"></script>
<script src="{% static 'partners/js/partners.js' %}"></script>
{% endblock after_app_js %}


{% comment %}
-------------------------------------------------------------------------------
TITULO SECUNDARIO
-------------------------------------------------------------------------------
{% endcomment %}
{% block page_secondary_title %}<span class="font-weight-light text-grey-600"> / Lista</span>{% endblock %}


{% comment %}
-------------------------------------------------------------------------------
SUBTITULO DE PAGINA
-------------------------------------------------------------------------------
{% endcomment %}
{% block page_subtitle %}{% endblock page_subtitle %}
{% block header_elements %}{% endblock header_elements %}


{% comment %}
-------------------------------------------------------------------------------
BREADCRUMB
-------------------------------------------------------------------------------
{% endcomment %}
{% block breadcrumb %}
    {{ block.super }}
    <a class="breadcrumb-item">Proveedores</a>
    <span class="breadcrumb-item active">Lista</span>
{% endblock breadcrumb %}

{% comment %} BREADCRUMB ELEMENTS {% endcomment %}
{% block breadcrumb_elements %}{% endblock breadcrumb_elements %}


{% comment %}
-------------------------------------------------------------------------------
CONTENT
-------------------------------------------------------------------------------
{% endcomment %}
{% block content %}
<div class="card">
    <div class="card-header bg-light header-elements-inline">
        <h5 class="card-title">Directorio de Proveedores</h5>
        <div class="header-elements">
            <div class="list-icons">
                <a target="_blank"  href="#" class="btn btn-sm btn-light ml-3"><i class="icon-database-add mr-2"></i> Registrar</a>
            </div>
        </div>
    </div>

    <table class="table table-xs provider-datatable">
        <thead>
            <tr>
                <th></th>
                <th>RUC</th>
                <th>Razón Social</th>
                <th>Activo</th>
                <th><span class="text-muted"><i class="icon-cog3"></i></span></th>
            </tr>
        </thead>
        <tbody>
            {% for vendor in object_list %}
            <tr>
                <td></td>
                <td><a href="{% url 'partners:partner-detail' vendor.pk %}">{{ vendor.fiscal_number }}</a></td>
                <td>{{ vendor.business_name }}</td>
                <td>
                    <span hidden>{{ vendor.is_active }}</span>
                    {% if vendor.is_active %}
                    <span class="text-success"><i class="icon-checkmark3"></i></span>
                    {% else %}
                    <span class="text-danger"><i class="icon-cross2"></i></span>
                    {% endif %}
                </td>
                <td>-</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}


{% comment %}
-------------------------------------------------------------------------------
FOOTER
-------------------------------------------------------------------------------
{% endcomment %}