moves/urls.py
from django.urls import path

from . import views


app_name = "moves"

urlpatterns = [
    path("", views.move_list, name="list"),
    path("<int:move_id>", views.move_detail, name="detail"),
    path("<int:move_id>/print", views.move_detail_print, name="print"),
]

projects/urls.py
from django.urls import include, path

from . import views


app_name = "projects"


requisitions_patterns = []

urlpatterns = [
    # Proyectos
    # -------------------------------------------------------------------------
    path("", views.ProjectList.as_view(), name="list"),
    path("<int:pk>/", views.detail, name="detail"),
    path("create/", views.ProjectCreate.as_view(), name="create"),

    # Proyectos & Requerimientos
    # -------------------------------------------------------------------------
    path(
        "<int:pk>/requisitions/",
        views.ProjectRequisitionList.as_view(),
        name="requisitions"
    ),
    path(
        "<int:pk>/requisitions/master",
        views.ProjectRequisitionMasterList.as_view(),
        name="requisitions_master"
    ),

    # Proyectos & Compras
    # -------------------------------------------------------------------------
    # path(
    #     "<int:pk>/purchases/",
    #     views.ProjectPurchaseList.as_view(),
    #     name="purchases"
    # ),
]

things/urls.py
from django.urls import path

from .views import (
    ThingList,
    ThingDetail,
)

app_name = "things"

urlpatterns = [
    path("", ThingList.as_view(), name="list"),
    path("<int:pk>", ThingDetail.as_view(), name="detail"),
]

warehouses/urls.py
from django.urls import path

from . import views


app_name = "warehouses"

urlpatterns = [
    path("", views.WarehouseListView.as_view(), name="list"),
    path("<int:pk>", views.WarehouseDetailView.as_view(), name="detail"),
    path(
        "<int:pk>/stock",
        views.WarehouseStockListView.as_view(),
        name="stock"
    ),
    path("<int:pk>/shippings", views.shippings),
    path("<int:pk>/arrivals", views.arrivals),
]

warehouses/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import gettext_lazy as _

from partners.models import Partner
from projects.models import Project

from sunqu.behaviors import Timestampable


User = get_user_model()


class Warehouse(Timestampable, models.Model):
    # Nombre
    name = models.CharField(_("name"), max_length=254)
    # Es virtual
    is_virtual = models.BooleanField(_("is virtual"), default=False)
    # Dirección
    address = models.TextField(_("address"), blank=True, default="")
    # Dirección Segunda Linea
    address_second_line = models.TextField(
        _("address second line"),
        blank=True,
        default=""
    )
    # Maps Link
    map_url = models.TextField(_("map url"), blank=True, default="")
    # Ubicación (ubigeo)
    location = models.CharField(
        _("location"),
        blank=True,
        default="",
        help_text=_("district, city, state"),
        max_length=254,
    )
    # Proyecto
    project = models.ForeignKey(
        Project,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name="warehouses",
        verbose_name=_("project")
    )
    # ¿Almacén activo?
    is_active = models.BooleanField(_("is active"), default=True)
    # Responsables de almacén
    storekeepers = models.ManyToManyField(User, through="Storekeeper")

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["name", "project"],
                name="unique_project_warehouse"
            )
        ]
        ordering = ["name"]
        verbose_name = _("warehouse")
        verbose_name_plural = _("warehouses")

    def __str__(self):
        if self.project:
            return f"{self.project} / {self.name}"
        else:
            return f"{self.name}"


class Storekeeper(Timestampable, models.Model):
    # Almacén
    warehouse = models.ForeignKey(
        Warehouse,
        on_delete=models.PROTECT,
        verbose_name=_("warehouse")
    )
    # Usuario
    user = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        verbose_name=_("user")
    )
    # Está activo
    is_active = models.BooleanField(_("is active"), default=True)
    # Fecha de ingreso
    joining_date = models.DateField(_("joining date"))
    # Fecha de salida
    leaving_date = models.DateField(_("leaving date"), blank=True, null=True)

    class Meta:
        verbose_name = _("storekeeper")
        verbose_name_plural = _("storekeepers")

    def __str__(self):
        return f"{self.warehouse} / {self.user}"

warehouses/views.py
from django.db.models import Count
from django.shortcuts import render, get_object_or_404
from django.views import generic


from .models import Storekeeper, Warehouse
from moves.models import Move
from stocks.models import Stock


class WarehouseListView(generic.ListView):
    model = Warehouse

    def get_queryset(self):
        queryset = Warehouse.objects.annotate(Count("stock"))
        return queryset


class WarehouseDetailView(generic.DetailView):
    model = Warehouse

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["storekeepers"] = Storekeeper.objects.filter(
            warehouse=self.object, is_active=True)
        return context


class WarehouseStockListView(generic.ListView):
    model = Stock
    template_name = "warehouses/warehouse_stock.html"

    def get_queryset(self):
        warehouse = self.kwargs.get("pk")
        return Stock.objects.filter(warehouse=warehouse)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["warehouse"] = get_object_or_404(
            Warehouse, pk=self.kwargs.get("pk")
        )
        return context


def shippings(request, pk):
    shippings = Move.objects.filter(origin=pk)
    return render(request, 'warehouses/shipping_list.html', {
        'object_list': shippings
    })


def arrivals(request, pk):
    arrivals = Move.objects.filter(destination=pk)
    return render(request, 'warehouses/arrival_list.html', {
        'object_list': arrivals
    })

warehouses/templates/warehouses/arrival_list.html
arrival_list

warehouses/templates/warehouses/shipping_list.html
shipping_list

warehouses/templates/warehouses/warehouse_base.html
{% extends "layouts/sidebar_main.html" %}
{% load static %}


{% comment %}
-------------------------------------------------------------------------------
TITULO DE VENTANA
-------------------------------------------------------------------------------
{% endcomment %}
{% block title %}Piwi - Almacenes{% endblock title %}


{% comment %}
-------------------------------------------------------------------------------
SIDEBAR IZQUIERDO
-------------------------------------------------------------------------------
{% endcomment %}
{% block navigation %}
<li class="nav-item-header"><div class="text-uppercase font-size-xs line-height-xs">Almacenes</div> <i class="icon-menu" title="Main"></i></li>
<li class="nav-item">
    <a href="{% url 'warehouses:list' %}" class="nav-link ">
        <i class="fas fa-city"></i>  
        <span>Almacenes</span>
    </a>
</li>
{% endblock navigation %}


{% comment %}
-------------------------------------------------------------------------------
TITULO DE PAGINA
-------------------------------------------------------------------------------
{% endcomment %}
{% block page_icon %}<i class="fas fa-city mr-2"></i>{% endblock page_icon %}
{% block page_title %}Almacenes{% endblock page_title %}


{% comment %}
-------------------------------------------------------------------------------
BREADCRUMB
-------------------------------------------------------------------------------
{% endcomment %}
{% block breadcrumb %}
    <a href="#" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Inicio</a>
    <a href="{% url 'warehouses:list' %}" class="breadcrumb-item">Almacenes</a>
{% endblock breadcrumb %}


{% comment %}
-------------------------------------------------------------------------------
ELEMENTOS DEL PIE DE PAGINA
-------------------------------------------------------------------------------
{% endcomment %}
{% block footer_elements %}{% endblock %}

warehouses/templates/warehouses/warehouse_detail.html
{% extends "warehouses/warehouse_base.html" %}
{% load static %}


{% comment %}
-------------------------------------------------------------------------------
THEME JS FILES
-------------------------------------------------------------------------------
{% endcomment %}
{% block before_app_js %}
<script src="{% static 'js/plugins/tables/footable/footable.min.js' %}"></script>
{% endblock before_app_js %}
{% block after_app_js %}
<script src="{% static 'warehouses/js/warehouse_detail.js' %}"></script>
{% endblock after_app_js %}


{% comment %}
-------------------------------------------------------------------------------
SUBTITULO DE PAGINA
-------------------------------------------------------------------------------
{% endcomment %}
{% block page_secondary_title %} <span class="font-weight-light text-grey-600">/ Detalle</span>{% endblock page_secondary_title %}
{% block page_subtitle %}Información de almacén {{ object.name }}{% endblock page_subtitle %}
{% block header_elements %}
<div class="header-elements d-none">
    <div class="d-flex justify-content-center">
        <a href="{% url 'warehouses:stock' object.pk %}" class="btn btn-link btn-float text-default"><i class="fas fa-boxes text-primary"></i><span>Existencias</span></a>
    </div>
</div>
{% endblock header_elements %}


{% comment %}
-------------------------------------------------------------------------------
BREADCRUMBS
-------------------------------------------------------------------------------
{% endcomment %}
{% block breadcrumb %}
    {{ block.super }}
    <span class="breadcrumb-item active">{{ object.name }}</span>
{% endblock breadcrumb %}


{% block breadcrumb_elements %}{% endblock breadcrumb_elements %}

{% block content %}
<div class="card">
    <div class="card-header bg-light header-elements-inline">
        <h5 class="card-title">Información de almacén</h5>
        <div class="header-elements">
            {# <button type="button" id="newWarehouse" class="btn btn-sm btn-primary"><i class="icon-add-to-list mr-2"></i> Nuevo</button> #}
            <a href="{% url 'admin:warehouses_warehouse_change' object.pk %}" class="btn btn-sm btn-primary"><i class="icon-database-edit2 mr-1"></i> Editar</a>
        </div>
    </div>
    <div class="card-body">
        <!-- Mapa -->
        {% if object.map_url == "" or object.map_url is None %}
        <div width="100%" style="background-color:silver; height:350px; text-align:center; vertical-align: middle; line-height: 350px;">
            <span class="lead">Mapa no disponible. Sin información de ubicación.</span>
        </div>
        {% else %}
        <iframe src="{{ object.map_url }}" width="100%" height="350" frameborder="0" style="border:0;"></iframe>
        {% endif %}
        <!-- /mapa -->

        <!-- Information -->
        <div class="row mt-3">
            <div class="col-lg-6">
                <dl class="row mb-0">
                    <div class="col-sm-4 text-sm-right">
                        <dt class="text-uppercase">Nombre:</dt>
                    </div>
                    <div class="col-sm-8 text-sm-left">
                        <dd class="mb-1">
                            {{ object.name }}
                        </dd>
                    </div>
                </dl>
                <dl class="row mb-0">
                    <div class="col-sm-4 text-sm-right">
                        <dt class="text-uppercase">Dirección:</dt>
                    </div>
                    <div class="col-sm-8 text-sm-left">
                        <dd class="mb-1">
                            {{ object.address }} {% if object.address2 != "" %}{{ object.address2 }}{% endif %}
                        </dd>
                    </div>
                </dl>
                <dl class="row mb-0">
                    <div class="col-sm-4 text-sm-right">
                        <dt class="text-uppercase">Ubigeo:</dt>
                    </div>
                    <div class="col-sm-8 text-sm-left">
                        <dd class="mb-1">
                            {{ object.location }}
                        </dd>
                    </div>
                </dl>
            </div>
            <div class="col-lg-6">
                <dl class="row mb-0">
                    <div class="col-sm-4 text-sm-right">
                        <dt class="text-uppercase">Proyecto:</dt>
                    </div>
                    <div class="col-sm-8 text-sm-left">
                        <dd class="mb-1">
                            <a href="{% url 'projects:detail' object.project.pk %}">CP/GW-{{ object.project }}-{{ object.project.award_date|date:"Y" }}</a>
                        </dd>
                    </div>
                </dl>
                <dl class="row mb-0">
                    <div class="col-sm-4 text-sm-right">
                        <dt class="text-uppercase">Estado:</dt>
                    </div>
                    <div class="col-sm-8 text-sm-left">
                        <dd class="mb-1">
                        {% if object.is_active %}
                            <span class="badge badge-success">Activo</span>
                        {% else %}
                            <span class="badge badge-danger">Inactivo</span>
                        {% endif %}
                        </dd>
                    </div>
                </dl>
            </div>
        </div>
        <!-- /information -->
    </div>
</div>

<div class="card">
    <div class="card-header header-elements-inline">
        <h6 class="card-title">Personal Asignado</h6>
        <div class="header-elements">
            <div class="list-icons ml-3">
                <a class="list-icons-item" data-action="collapse"></a>
            </div>
        </div>
    </div>

    <table class="table table-togglable">
        <thead class="text-uppercase">
            <tr>
                <th data-toggle="true">Nombres y Apellidos</th>
                <th data-hide="phone">Nro. Doc.</th>
                <th data-hide="phone,tablet">Tel.</th>
                <th data-hide="phone,tablet">Email</th>
            </tr>
        </thead>
        <tbody>
        {% for storekeeper in storekeepers %}
            <tr>
                <td>{{ storekeeper.user.collaborator.full_name }}</td>
                <td>{{ storekeeper.user.collaborator.idn }}</td>
                <td>{{ storekeeper.user.collaborator.phone }}</td>
                <td><a href="mailto:{{ storekeeper.user.email }}">{{ storekeeper.user.email }}</a></td>
            </tr>
        {% empty %}
        <tr>
            <td class="text-center text-grey" colspan=4>Sin personal asignado</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}

warehouses/templates/warehouses/warehouse_list.html
{% extends "./warehouse_base.html" %}
{% load static %}


{% comment %}
-------------------------------------------------------------------------------
THEME JS FILES
-------------------------------------------------------------------------------
{% endcomment %}
{% block before_app_js %}
<script src="{% static 'js/plugins/tables/datatables/datatables.min.js' %}"></script>
<script src="{% static 'js/plugins/tables/datatables/extensions/responsive.min.js' %}"></script>
<script src="{% static 'js/plugins/forms/selects/select2.min.js' %}"></script>
{% endblock before_app_js %}
{% block after_app_js %}
<script src="{% static 'js/config/datatables/datatable_responsive.js' %}"></script>
<script src="{% static 'warehouses/js/warehouse_list.js' %}"></script>
{% endblock after_app_js %}


{% comment %}
-------------------------------------------------------------------------------
THEME JS FILES
-------------------------------------------------------------------------------
{% endcomment %}
{% block vue_js %}{% endblock vue_js %}


{% comment %}
-------------------------------------------------------------------------------
SUBTITULO DE PAGINA
-------------------------------------------------------------------------------
{% endcomment %}
{% block page_subtitle %}{% endblock page_subtitle %}
{% block header_elements %}{% endblock header_elements %}


{% comment %}
-------------------------------------------------------------------------------
BREADCRUMBS
-------------------------------------------------------------------------------
{% endcomment %}
{% block breadcrumb %}
    {{ block.super }}
    <span class="breadcrumb-item active">Lista</span>
{% endblock breadcrumb %}
{% block breadcrumb_elements %}{% endblock %}


{% comment %}
-------------------------------------------------------------------------------
CONTENIDO
-------------------------------------------------------------------------------
{% endcomment %}
{% block content %}
<div class="card">
    <div class="card-header bg-light header-elements-inline">
        <h5 class="card-title">Almacenes Registrados</h5>
        <div class="header-elements">
            <a href="{% url 'admin:warehouses_warehouse_add' %}" class="btn btn-sm btn-primary"><i class="icon-add-to-list mr-1"></i> Nuevo</a>
        </div>
    </div>

    <table class="table datatable-responsive">
        <thead>
            <tr class="text-uppercase">
                <th></th>
                <th data-priority="1">Nombre</th>
                <th>Estado</th>
                <th>Artículos</th>
                <th>Valor</th>
            </tr>
        </thead>
        <tbody>
        {% for warehouse in object_list %}
            <tr>
                <td></td>
                <td>
                    <p class="mb-0 font-weight-semibold"><a href="{{ warehouse.id }}">{{ warehouse.project }} / {{ warehouse.name }}</a></p>
                    <span class="text-muted">{{ warehouse.address|upper }}</span>
                </td>
                <td>
                    {% if warehouse.is_active %}
                    <span class="badge bg-success">Activo</span>
                    {% else %}
                    <span class="badge bg-danger">Inactivo</span>
                    {% endif %}
                </td>
                <td class="text-center">{{ warehouse.stock__count }}</td>
                <td>S/ 125,452.20</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}


{% comment %}
-------------------------------------------------------------------------------
ELEMENTOS DEL PIE DE PAGINA
-------------------------------------------------------------------------------
{% endcomment %}
{% block footer_elements %}{% endblock %}


{% comment %}
-------------------------------------------------------------------------------
SCRIPTS ADICIONALES
-------------------------------------------------------------------------------
{% endcomment %}
{% block script %}{% endblock script %}

warehouses/templates/warehouses/warehouse_stock.html
{% extends "warehouses/warehouse_base.html" %}
{% load static %}


{% comment %}
-------------------------------------------------------------------------------
THEME JS FILES
-------------------------------------------------------------------------------
{% endcomment %}
{% block before_app_js %}
<script src="{% static 'js/plugins/tables/datatables/datatables.min.js' %}"></script>
<script src="{% static 'js/plugins/tables/datatables/extensions/responsive.min.js' %}"></script>
<script src="{% static 'js/plugins/forms/selects/select2.min.js' %}"></script>
{% endblock before_app_js %}
{% block after_app_js %}
<script src="{% static 'js/config/datatables/datatable_responsive.js' %}"></script>
<script src="{% static 'warehouses/js/warehouse_stock.js' %}"></script>
{% endblock after_app_js %}


{% comment %}
-------------------------------------------------------------------------------
SUBTITULO DE PAGINA
-------------------------------------------------------------------------------
{% endcomment %}
{% block page_secondary_title %} <span class="font-weight-light text-grey-600">/ Existencias</span>{% endblock page_secondary_title %}
{% block page_subtitle %}Lista de artículos existentes en {{ warehouse }}{% endblock page_subtitle %}
{% block header_elements %}{% endblock header_elements %}


{% comment %}
-------------------------------------------------------------------------------
BREADCRUMBS
-------------------------------------------------------------------------------
{% endcomment %}
{% block breadcrumb %}
{{ block.super }}
<a href="{% url 'warehouses:detail' warehouse.pk %}" class="breadcrumb-item">{{ warehouse.name }}</a>
<span class="breadcrumb-item active">Existencias</span>
{% endblock breadcrumb %}


{% comment %}
-------------------------------------------------------------------------------
CONTENIDO
-------------------------------------------------------------------------------
{% endcomment %}
{% block content %}
<div class="card">
    <div class="card-header bg-light header-elements-inline">
        <h5 class="card-title">Artículos existentes</h5>
    </div>
    
    <table class="table datatable-responsive-column-controlled">
        <thead>
            <tr>
                <th></th>
                <th>Código</th>
                <th>Artículo</th>
                <th style="width: 115px;">Cant.</th>
                <th>U.M.</th>
            </tr>
        </thead>
        <tbody>
            {% for object in object_list %}
            <tr>
                <td></td>
                <td><a href="{% url 'things:detail' object.thing.pk %}">{{ object.thing.code }}</a></td>
                <td>{{ object.thing.description }}</td>
                <td>{{ object.quantity }}</td>
                <td>{{ object.thing.default_measure.abbreviation }}</td>
            </tr>                
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}


{% comment %}
-------------------------------------------------------------------------------
ELEMENTOS DEL PIE DE PAGINA
-------------------------------------------------------------------------------
{% endcomment %}
{% block footer_elements %}{% endblock %}


{% comment %}
-------------------------------------------------------------------------------
SCRIPTS ADICIONALES
-------------------------------------------------------------------------------
{% endcomment %}
{% block script %}{% endblock script %}