moves/urls.py
from django.urls import path

from . import views


app_name = "moves"

urlpatterns = [
    path("", views.move_list, name="list"),
    path("<int:move_id>", views.move_detail, name="detail"),
    path("<int:move_id>/print", views.move_detail_print, name="print"),
]

partners/urls.py
from django.urls import path
from . import views


app_name = "partners"

urlcustomers = []
urlproviders = []

urlpatterns = [
    # Socios de Negocio / Proveedores
    path("", views.PartnerList.as_view(), name="partner-list"),
    path("<int:pk>/", views.PartnerDetail.as_view(), name="partner-detail"),
    path("providers/", views.ProviderList.as_view(), name="provider-list"),
    path("customers/", views.CustomerList.as_view(), name="customer-list"),
    # Socios de Negocio / Clientes
    # Socios de Negocio / Proveedores / Contactos
    # path("providers/<int:pk>/", views.ProviderDetail.as_view(), name="detail"),
]

projects/urls.py
from django.urls import include, path

from . import views


app_name = "projects"


requisitions_patterns = []

urlpatterns = [
    # Proyectos
    # -------------------------------------------------------------------------
    path("", views.ProjectList.as_view(), name="list"),
    path("<int:pk>/", views.detail, name="detail"),
    path("create/", views.ProjectCreate.as_view(), name="create"),

    # Proyectos & Requerimientos
    # -------------------------------------------------------------------------
    path(
        "<int:pk>/requisitions/",
        views.ProjectRequisitionList.as_view(),
        name="requisitions"
    ),
    path(
        "<int:pk>/requisitions/master",
        views.ProjectRequisitionMasterList.as_view(),
        name="requisitions_master"
    ),

    # Proyectos & Compras
    # -------------------------------------------------------------------------
    # path(
    #     "<int:pk>/purchases/",
    #     views.ProjectPurchaseList.as_view(),
    #     name="purchases"
    # ),
]

purchases/api/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path("", views.ListCreatePurchase.as_view(), name="purchase-list"),
    path(
        "<int:pk>/",
        views.RetrieveUpdateDestroyPurchase.as_view(),
        name="purchase-detail"
    ),
]

purchases/urls.py
from django.urls import path

from . import views
from .views import PurchaseList


app_name = "purchases"

urlpatterns = [
    path("", PurchaseList.as_view(), name="list"),
    path("create/", views.PurchaseCreate.as_view(), name="create"),
    path("<int:pk>/", views.PurchaseDetail.as_view(), name="detail"),
    path("<int:pk>/invoices/", views.InvoiceList.as_view(), name="invoices"),
    path("<int:pk>/moves/", views.MoveList.as_view(), name="moves"),
]

requisitions/urls.py
from django.urls import include, path

from .views import (
    ProjectRequisitionConcatenated,
    RequisitionRegister,
    RequisitionList,
    RequisitionDetail,
    RequisitionThingList,
    RequestedItemList,
    RequisitionPurchaseList,
    ThingRequiredList,
    thing_requisitions_list,
)

app_name = "requisitions"

purchases_patterns = []

things_patterns = [
    path("", RequestedItemList.as_view(), name="requested"),
    path("<int:pk>", ThingRequiredList.as_view(), name="detail")
]

urlpatterns = [
    path("add/", RequisitionRegister.as_view(), name="add"),
    path("", RequisitionList.as_view(), name="list"),
    path("<int:pk>/", RequisitionDetail.as_view(), name="detail"),
    path("lines/", RequisitionThingList.as_view(), name="lines"),
    path(
        "<int:pk>/purchases/",
        RequisitionPurchaseList.as_view(),
        name="purchases"
    ),
    # path("master/", RequestedItemList.as_view(), name="requested-item-list"),
    # Things / Artículos
    # -------------------------------------------------------------------------
    path(
        "things/",
        include(
            (things_patterns, "things"),
            namespace="things"
        )
    ),
    path("test/", ProjectRequisitionConcatenated.as_view(), name="test")
]

purchases/models.py
from decimal import Decimal

from django.contrib.auth import get_user_model
from django.db import models
from django.utils.translation import gettext as _

from contacts.models import Contact
from partners.models import Partner
from projects.models import Project
from quotations.models import Quotation
from requisitions.models import Requisition
from sunat.models import Tax
from sunqu.behaviors import Timestampable
from things.models import Thing
from universal.models import Currency, UnitOfMeasurement


User = get_user_model()


class Purchase(Timestampable, models.Model):
    STATE_CREATED = "cr"  # creado
    STATE_OPENED = "op"  # abierto
    STATE_CLOSED = "cl"  # cerrado
    STATE_CANCELED = "cn"  # cancelado
    STATE_CHOICES = (
        (STATE_CREATED, _("created")),
        (STATE_OPENED, _("opened")),
        (STATE_CLOSED, _("closed")),
        (STATE_CANCELED, _("canceled")),
    )
    # Código
    code = models.PositiveIntegerField(
        _("code"),
        blank=True,
        unique_for_year="created_at"
    )
    # Usuario / Autor
    author = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        verbose_name=_("author")
    )
    # Cotizaciones
    quotations = models.ManyToManyField(
        Quotation,
        blank=True
    )
    # Moneda
    currency = models.ForeignKey(
        Currency,
        on_delete=models.PROTECT,
        verbose_name=_("currency")
    )
    # Socio de negocio / Proveedor
    vendor = models.ForeignKey(
        Partner,
        on_delete=models.PROTECT,
        related_name="purchases",
        verbose_name=_("vendor")
    )
    # Contacto de proveedor
    contact = models.ForeignKey(
        Contact,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name="purchases",
        verbose_name=_("contact")
    )
    # Proyecto
    project = models.ForeignKey(
        Project,
        on_delete=models.PROTECT,
        related_name='purchases',
        verbose_name=_("project")
    )
    # Base imponible
    untaxed_amount = models.DecimalField(
        _("untaxed amount"),
        max_digits=13,
        decimal_places=2,
        default=0.000
    )
    # Monto Impuesto
    tax_amount = models.DecimalField(
        _("tax amount"),
        max_digits=13,
        decimal_places=2,
        default=0.000
    )
    # Monto total
    total_amount = models.DecimalField(
        _("total amount"),
        max_digits=13,
        decimal_places=2,
        default=0.000
    )
    # Observación
    observation = models.TextField(_("observation"), default="")
    # Términos y condiciones
    terms_conditions = models.TextField(_("terms and conditions"), default="")
    # Estado
    state = models.CharField(
        _("state"),
        max_length=2,
        choices=STATE_CHOICES,
        default=STATE_CREATED
    )
    # Requerimiento
    requisition = models.ForeignKey(
        Requisition,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name="purchases",
        verbose_name=_("requisition")
    )

    class Meta:
        verbose_name = _("purchase")
        verbose_name_plural = _("purchases")
        ordering = ["-code"]

    def __str__(self):
        from sunqu.utils import codify
        string_code = codify(self.code, 5)
        created_year = self.created_at.strftime("%y")
        return f"{string_code}-{created_year}"

    def save(self, *args, **kwargs):
        # nothing to do
        return super().save(*args, **kwargs)

    def set_untaxed_amount(self):
        pass

    def set_tax_amount(self):
        pass

    def set_total_amount(self):
        pass


class PurchaseThing(models.Model):
    # Compra
    purchase = models.ForeignKey(
        Purchase,
        on_delete=models.CASCADE,
        related_name="purchase_lines"
    )
    # Código externo del artículo
    external_code = models.CharField(
        _("external code"),
        blank=True,
        default="",
        max_length=80
    )
    # Demanda
    demand = models.FloatField(_("demand"), default=0.00)
    # Unidad de medida
    uom = models.ForeignKey(
        UnitOfMeasurement,
        on_delete=models.PROTECT,
        verbose_name=_("unit of measurement")
    )
    # Artículo
    thing = models.ForeignKey(
        Thing,
        on_delete=models.PROTECT,
        related_name="purchases",
        verbose_name=_("thing")
    )
    # Precio Unitario
    unit_price = models.DecimalField(
        _("unit price"),
        decimal_places=4,
        default=Decimal(0.00),
        max_digits=15
    )
    # Impuestos (m2m)
    taxes = models.ManyToManyField(
        Tax,
        blank=True
    )
    # Valor unitario
    unit_value = models.DecimalField(
        _("unit value"),
        decimal_places=4,
        default=Decimal(0.00),
        max_digits=15,
    )
    # Subtotal
    subtotal = models.DecimalField(
        _("subtotal"),
        decimal_places=4,
        default=0.000,
        max_digits=15
    )
    # Cantidad Recibida
    quantity_received = models.DecimalField(
        _("received quantity"),
        max_digits=5,
        decimal_places=2,
        default=0.00
    )
    # Cantidad Facturada
    quantity_billed = models.DecimalField(
        _("billed quantity"),
        max_digits=5,
        decimal_places=2,
        default=0.00
    )
    # Tipo de Gasto
    # expense_type = models.ForeignKey(
    #     ExpenseType,
    #     null=True,
    #     on_delete=models.SET_NULL,
    #     verbose_name=_("expense type")
    # )

    def __str__(self):
        return "{0}".format(self.thing)

purchases/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from .models import Purchase, PurchaseLine


class PurchaseForm(forms.ModelForm):

    code = forms.IntegerField(
        label=_("Code"),
        disabled=True,
        required=False,
    )

    class Meta:
        model = Purchase
        fields = "__all__"

purchases/api/views.py
from rest_framework import generics

from ..models import Purchase, PurchaseLine
from . import serializers


class ListCreatePurchase(generics.ListCreateAPIView):
    queryset = Purchase.objects.all()
    serializer_class = serializers.PurchaseSerializer


class RetrieveUpdateDestroyPurchase(generics.RetrieveUpdateDestroyAPIView):
    queryset = Purchase.objects.all()
    serializer_class = serializers.PurchaseSerializer

purchases/views.py
from django.apps import apps
from django.db.models import Count
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView


from .models import Purchase
from invoices.models import Invoice
from moves.models import Move
from projects.models import Project


class PurchaseList(LoginRequiredMixin, ListView):
    model = Purchase

    def get_queryset(self):
        if apps.is_installed("moves"):
            queryset = Purchase.objects.annotate(
                moves_count=Count("moves")
            ).annotate(
                invoices_count=Count("invoices")
            ).order_by("-code")

        print("<Moves> isn't installed.")

        if apps.is_installed("invoices"):
            queryset = Purchase.objects.annotate(
                moves_count=Count("moves")
            ).annotate(
                invoices_count=Count("invoices")
            ).order_by("-code")

        print("<Invoices> isn't installed.")

        queryset = Purchase.objects.order_by("-code")
        return queryset


# TODO: Generar "compra" con formulario via API
class PurchaseCreate(TemplateView):
    template_name = "purchases/purchase_form.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["projects"] = Project.objects.all()
        return context


class PurchaseDetail(DetailView):
    model = Purchase

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Cantidad de atenciones (guias de remisión)
        context["moves_count"] = self.object.moves.count()
        # Cantidad de comprobantes
        context["invoices_count"] = self.object.invoices.count()
        return context

    def get_queryset(self):
        queryset = Purchase.objects.select_related(
            "contact",
            "currency",
            "vendor",
            "project",
            "requisition",
            "author"
        ).prefetch_related(
            "purchase_lines"
        ).all()
        return queryset


class MoveList(ListView):
    model = Move

    def get_queryset(self):
        queryset = Move.objects.filter(purchase=self.kwargs.get("pk"))
        return queryset

    def get_template_names(self):
        return "purchases/purchase_moves_list.html"


class InvoiceList(ListView):
    model = Invoice

    def get_queryset(self):
        queryset = Invoice.objects.filter(purchase=self.kwargs.get("pk"))
        return queryset

    def get_template_names(self):
        return "purchases/purchase_invoice_list.html"

purchases/templates/purchases/purchase_detail.html
{% extends "purchases/purchase_base_dual.html" %}
{% load static %}

{% comment %}
-------------------------------------------------------------------------------
JS Files
-------------------------------------------------------------------------------
{% endcomment %}


{% comment %}
-------------------------------------------------------------------------------
TITULO SECUNDARIO
-------------------------------------------------------------------------------
{% endcomment %}
{% block page_secondary_title %}<span class="font-weight-light text-grey-600"> / Detalle</span>{% endblock page_secondary_title %}
{% block page_subtitle %}Detalle de compra {{ object }}{% endblock page_subtitle %}
{% block header_elements %}{% endblock header_elements %}


{% comment %}
-------------------------------------------------------------------------------
BREADCRUMB
-------------------------------------------------------------------------------
{% endcomment %}
{% block breadcrumb %}
    {{ block.super }}
    <span class="breadcrumb-item active">{{ object }}</span>
{% endblock breadcrumb %}
{% block breadcrumb_elements %}{% endblock breadcrumb_elements %}


{% comment %}
-------------------------------------------------------------------------------
LEFT CONTENT
-------------------------------------------------------------------------------
{% endcomment %}
{% block left_content %}
<div class="card">
    <div class="card-header bg-light header-elements-inline">
        <h6 class="card-title">OC #{{ object }}</h6>
        <div class="header-elements">
            <a target="_blank" href="{% url 'admin:purchases_purchase_change' object.pk %}" class="btn btn-light btn-sm ml-2">
                <i class="icon-database-edit2 mr-2"></i> Editar
            </a>
            <button type="button" class="btn btn-light btn-sm ml-2">
                <i class="icon-printer mr-2"></i> Imprimir
            </button>
        </div>
    </div>
    
    <!-- Purchase body -->
    <div class="card-body">
        <div class="row mb-2 mb-md-4 align-items-center">
            <div class="col-sm-6">
                <img src="{% static 'images/logo_gw.png' %}" class="mb-3 mt-2" alt="" style="width: 200px;">
                <ul class="list list-unstyled mb-0">
                    <li class="mt-0">Av. Calmell Del Solar Nro. 626</li>
                    <li class="mt-0">Huancayo, Junín, Perú</li>
                    <li class="mt-0">+51 (64) 600-445</li>
                </ul>
            </div>

            <div class="col-sm-6">
                <div class="text-sm-right">
                    <h4 class="font-weight-bold mt-3 mt-sm-2 mb-0">OC #{{ object }}</h4>
                    <ul class="list list-unstyled">
                        <li><span class="text-muted font-weight-light h5">{{ object.created_at|date:"F j, Y" }}</span></li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="row">
            <!-- Provider information -->
            <div class="col-12 col-xl-6">
                <table class="table table-borderless">
                    <tbody>
                        <tr>
                            <th class="text-muted lead pl-0 pt-xl-0 pt-2">Emitido a:</th>
                        </tr>
                        <tr>
                            <th class="lead font-weight-semibold text-uppercase p-0">
                                {% if object.vendor.parent %}
                                {{ object.vendor.parent.business_name }}
                                {% else %}
                                {{ object.vendor.business_name }}
                                {% endif %}
                            </th>
                        </tr>
                        <tr>
                            <td class="font-size-lg pl-0 py-1">{{ object.vendor.identity_number }}</td>
                        </tr>
                        <tr>
                            <td class="p-0 text-uppercase">{{ object.vendor.address }}</td>
                        </tr>
                        <tr>
                            <td class="p-0 text-uppercase">{{ object.vendor.address2 }}</td>
                        </tr>
                        <tr>
                            <td class="p-0 text-uppercase">{{ object.vendor.ubigeo }}</td>
                        </tr>
                        {% if object.contact %}
                            <tr>
                                <td class="font-weight-semibold text-uppercase pl-0 pt-2 pb-0">{{ object.contact.branch_office }}</td>
                            </tr>
                            <tr>
                                <td class="p-0">{{ object.contact.first_name }} {{ object.contact.last_name }}</td>
                            </tr>
                            <tr>
                                <td class="p-0"><a href="mailto:{{ object.contact.email }}">{{ object.contact.email }}</a></td>
                            </tr>
                            <tr>
                                <td class="p-0">
                                    <a href="phone:{{ object.contact.phones|first }}">{{ object.contact.phones|first }}</a>
                                </td>
                            </tr>
                        {% endif %}
                    </tbody>
                </table>
            </div>
            <!-- /provider information -->

            <div class="col-12 col-xl-6">
                <table class="table table-borderless">
                    <tbody>
                        <tr>
                            <th class="text-muted lead pl-0 pt-xl-0 pt-4" colspan="2">Información adicional:</th>
                        </tr>
                        <tr class="lead font-weight-semibold">
                            <th class="p-0 pb-2" style="white-space: nowrap;">Deuda Total:</th>
                            <td class="p-0  pb-2 text-right" style="width: 100%;">{{ object.currency.symbol }} {{ object.amount_total|floatformat:2 }}</td>
                        </tr>
                        <tr>
                            <th class="p-0">Moneda:</th>
                            <td class="p-0 text-right" style="width: 100%;">
                            {% if object.currency.name_plural != "" %}
                                {{ object.currency.name_plural }}
                            {% else %}
                                {{ object.currency.name }}
                            {% endif %}
                            </td>
                        </tr>
                        <tr>
                            <th class="p-0">Autor:</th>
                            <td style="width: 100%;" class="p-0 text-right text-uppercase">{{ object.author.get_full_name }}</td>
                        </tr>
                        <tr>
                            <th class="p-0">Proyecto:</th>
                            <td style="width: 100%;" class="p-0 text-right"><a href="{% url 'projects:detail' object.project.pk %}">{{ object.project }}</a></td>
                        </tr>
                        {% if object.requisition %}
                        <tr>
                            <th class="p-0">Requerimiento:</th>
                            <td style="width: 100%;" class="p-0 text-right"><a href="{% url 'requisitions:detail' object.requisition.pk %}">{{ object.requisition }}</a></td>
                        </tr>
                        {% endif %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <div class="table-responsive">
        <table class="table table-sm">
            <thead>
                <tr class="text-uppercase">
                    <th style="min-width:300px">Descripcion</th>
{#                    <th class="text-nowrap">V. Unit.</th>#}
                    <th class="text-nowrap">P. Unit.</th>
                    <th class="text-nowrap">Cant.</th>
                    <th class="text-nowrap">V. Venta.</th>
                </tr>
            </thead>
            <tbody>
                {% for line in object.purchase_lines.all %}
                <tr>
                    <td>
                        <span class="mb-0">{{ line.thing.description }}</span><br>
                        <span class="text-muted small">{{ line.external_code }}</span>
                    </td>
{#                    <td>{{ line.price_unit|floatformat:3 }}</td>#}
                    <td>{{ line.price_unit|floatformat:3 }}</td>
                    <td>{{ line.demand }}</td>
                    <td class="text-right"><span class="font-weight-semibold">{{ line.price_subtotal|floatformat:2 }}</span></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="card-body">
        <div class="d-md-flex flex-md-wrap">
            <div class="pt-2 mb-3">
                <h6 class="mb-3">Términos y Condiciones</h6>
                <div class="mb-3 text-muted">
                    <p>{{ object.terms_conditions|safe }}</p>
                </div>
            </div>

            <div class="pt-2 mb-3 wmin-md-400 ml-auto">
                {% comment %} <h6 class="mb-3">Total</h6> {% endcomment %}
                <div class="table-responsive">
                    <table class="table">
                        <tbody>
                            <tr>
                                <th>Subtotal:</th>
                                <td class="text-right pr-0">{{ object.currency.symbol }} {{ object.amount_untaxed|floatformat:2 }}</td>
                            </tr>
                            <tr>
                                <th>IGV: <span class="font-weight-normal">(18%)</span></th>
                                <td class="text-right pr-0">{{ object.currency.symbol }} {{ object.amount_tax|floatformat:2 }}</td>
                            </tr>
                            <tr>
                                <th>Total:</th>
                                <td class="text-right text-primary pr-0"><h5 class="font-weight-semibold">{{ object.currency.symbol }} {{ object.amount_total|floatformat:2 }}</h5></td>
                            </tr>
                        </tbody>
                    </table>
                </div>

                <div class="text-right mt-3">
                    <button type="button" class="btn btn-primary btn-labeled btn-labeled-left"><b><i class="icon-paperplane"></i></b> Send invoice</button>
                </div>
            </div>
        </div>
    </div>

    <div class="card-footer">
        <span class="text-muted">Thank you for using Limitless. This invoice can be paid via PayPal, Bank transfer, Skrill or Payoneer. Payment is due within 30 days from the date of delivery. Late payment is possible, but with with a fee of 10% per month. Company registered in England and Wales #6893003, registered office: 3 Goodman Street, London E1 8BF, United Kingdom. Phone number: 888-555-2311</span>
    </div>
</div>
{% endblock left_content %}


{% comment %}
-------------------------------------------------------------------------------
RIGHT CONTENT
-------------------------------------------------------------------------------
{% endcomment %}
{% block sidebar_content %}
<div class="card">
    <div class="card-header bg-light header-elements-inline">
        <h6 class="card-title">Operaciones</h6>
        <div class="header-elements">
            <div class="list-icons">
                <a class="list-icons-item" data-action="collapse"></a>
            </div>
        </div>
    </div>

    <div class="card-body p-0">
        <ul class="nav nav-sidebar" data-nav-type="accordion">
            <li class="nav-item">
                <a href="{% url 'purchases:invoices' object.pk %}" class="nav-link">
                    <i class="fas fa-file-invoice-dollar mr-3"></i>
                    Comprobantes
                    <span class="badge bg-primary badge-pill ml-auto">{{ invoices_count }}</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="{% url 'purchases:moves' object.pk %}" class="nav-link">
                    <i class="fas fa-truck mr-3"></i>
                    Despachos
                    <span class="badge bg-primary badge-pill ml-auto">{{ moves_count }}</span>
                </a>
            </li>
        </ul>
    </div>
</div>
{% endblock sidebar_content %}

purchases/templates/purchases/purchase_invoice_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% for invoice in object_list %}
    <li>{{ invoice }} -> <a href="{{ invoice.invoice_url }}">Ver</a></li>
    {% endfor %}
</body>
</html>

purchases/templates/purchases/purchase_list.html
{% extends "purchases/purchase_base.html" %}
{% load static %}

{% comment %}
-------------------------------------------------------------------------------
JS Files
-------------------------------------------------------------------------------
{% endcomment %}
{% block before_app_js %}
<script src="{% static 'js/plugins/tables/datatables/datatables.min.js' %}"></script>
<script src="{% static 'js/plugins/tables/datatables/extensions/responsive.min.js' %}"></script>
<script src="{% static 'js/plugins/forms/selects/select2.min.js' %}"></script>
{% endblock before_app_js %}
{% block after_app_js %}
<script src="{% static 'js/config/datatables/datatable_responsive.js' %}"></script>
<script src="{% static 'purchases/js/purchase_list.js' %}"></script>
{% endblock after_app_js %}


{% comment %}
-------------------------------------------------------------------------------
TITULO SECUNDARIO
-------------------------------------------------------------------------------
{% endcomment %}
{% block page_secondary_title %}<span class="font-weight-light text-grey-600"> / Lista</span>{% endblock %}


{% comment %}
-------------------------------------------------------------------------------
SUBTITULO DE PAGINA
-------------------------------------------------------------------------------
{% endcomment %}
{% block page_subtitle %}{% endblock page_subtitle %}
{% block header_elements %}{% endblock header_elements %}


{% comment %}
-------------------------------------------------------------------------------
BREADCRUMB
-------------------------------------------------------------------------------
{% endcomment %}
{% block breadcrumb %}
    {{ block.super }}
    <span class="breadcrumb-item active">Lista</span>
{% endblock breadcrumb %}

{% comment %} BREADCRUMB ELEMENTS {% endcomment %}
{% block breadcrumb_elements %}
<div class="header-elements d-none">
    <div class="breadcrumb justify-content-center">
        <a href="{% url 'purchases:list' %}" class="breadcrumb-elements-item dropdown-toggle" data-toggle="dropdown">
            <i class="fas fa-filter mr-2"></i> Filtrar
        </a>
        <div class="dropdown-menu dropdown-menu-right">
            <a href="#" class="dropdown-item"><i class="icon-user-lock"></i> Pendientes</a>
            <a href="#" class="dropdown-item"><i class="icon-statistics"></i> En Progreso</a>
            <a href="#" class="dropdown-item"><i class="icon-statistics"></i> Atendidos</a>
            <a href="#" class="dropdown-item"><i class="icon-accessibility"></i> Anulados</a>
            <div class="dropdown-divider"></div>
            <a href="{% url 'requisitions:list' %}" class="dropdown-item"><i class="icon-gear"></i> Mostrar todo</a>
        </div>
    </div>
</div>
{% endblock breadcrumb_elements %}


{% comment %}
-------------------------------------------------------------------------------
CONTENT
-------------------------------------------------------------------------------
{% endcomment %}
{% block content %}
<div class="card">
    <div class="card-header bg-light header-elements-inline">
        <h5 class="card-title">Compras</h5>
        <div class="header-elements">
{#            <a href="#" class="btn btn-sm btn-light"><i class="icon-file-upload mr-2"></i> Importar</a>#}
            <a target="_blank"  href="{% url 'admin:purchases_purchase_add' %}" class="btn btn-sm btn-light ml-3"><i class="icon-database-add mr-2"></i> Nueva</a>
{#            <a href="{% url 'admin:purchases_purchase_add' %}" class="btn btn-sm btn-primary ml-3"><i class="icon-add-to-list mr-2"></i> Nueva</a>#}
        </div>
    </div>
    <table class="table datatable-responsive">
        <thead>
            <tr>
                <th></th>
                <th>#</th>
                <th>FECHA</th>
                <th>PROVEEDOR</th>
                <th>TOTAL</th>
                <th>ESTADO</th>
                <th>PROYECTO</th>
                <th><i class="fas fa-truck"></i></th>
                <th><i class="fas fa-file-invoice-dollar"></i></th>
                <th>COLABORADOR</th>
            </tr>
        </thead>
        <tbody>
            {% for purchase in object_list %}
            <tr>
                <td></td>
                <td class="text-nowrap"><a href="{% url 'purchases:detail' purchase.pk %}">{{ purchase }}</a></td>
                <td class="text-nowrap">{{ purchase.created_at|date:"Y-m-d" }}</td>
                <td class="text-nowrap">
                    <a href="{% url 'partners:detail' purchase.vendor.pk %}">
                        {{ purchase.vendor.business_name|truncatewords:3 }}
                    </a>
                </td>
                <td class="text-nowrap text-right">{{ purchase.currency.symbol }} {{ purchase.amount_total }}</td>
                <td>
                    {% if purchase.state == "is" %}
                    <span class="badge badge-primary">{{ purchase.get_state_display }}</span>
                    {% elif purchase.state == "cl" %}
                    <span class="badge badge-success">{{ purchase.get_state_display }}</span>
                    {% elif purchase.state == "cn" %}
                    <span class="badge badge-danger">{{ purchase.get_state_display }}</span>
                    {% endif %}
                </td>
                <td><a href="{% url 'projects:detail' purchase.project.pk %}">{{ purchase.project }}</a></td>
                <td>{{ purchase.moves_count}}</td>
                <td>{{ purchase.invoices_count }}</td>
                <td>{{ purchase.author.get_full_name }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}


{% comment %}
-------------------------------------------------------------------------------
FOOTER
-------------------------------------------------------------------------------
{% endcomment %}