moves/urls.py
from django.urls import path

from . import views


app_name = "moves"

urlpatterns = [
    path("", views.move_list, name="list"),
    path("<int:move_id>", views.move_detail, name="detail"),
    path("<int:move_id>/print", views.move_detail_print, name="print"),
]

projects/urls.py
from django.urls import include, path

from . import views


app_name = "projects"


requisitions_patterns = []

urlpatterns = [
    # Proyectos
    # -------------------------------------------------------------------------
    path("", views.ProjectList.as_view(), name="list"),
    path("<int:pk>/", views.detail, name="detail"),
    path("create/", views.ProjectCreate.as_view(), name="create"),

    # Proyectos & Requerimientos
    # -------------------------------------------------------------------------
    path(
        "<int:pk>/requisitions/",
        views.ProjectRequisitionList.as_view(),
        name="requisitions"
    ),
    path(
        "<int:pk>/requisitions/master",
        views.ProjectRequisitionMasterList.as_view(),
        name="requisitions_master"
    ),

    # Proyectos & Compras
    # -------------------------------------------------------------------------
    # path(
    #     "<int:pk>/purchases/",
    #     views.ProjectPurchaseList.as_view(),
    #     name="purchases"
    # ),
]

purchases/urls.py
from django.urls import path

from . import views
from .views import PurchaseList


app_name = "purchases"

urlpatterns = [
    path("", PurchaseList.as_view(), name="list"),
    path("create/", views.PurchaseCreate.as_view(), name="create"),
    path("<int:pk>/", views.PurchaseDetail.as_view(), name="detail"),
    path("<int:pk>/invoices/", views.InvoiceList.as_view(), name="invoices"),
    path("<int:pk>/moves/", views.MoveList.as_view(), name="moves"),
]

requisitions/api/urls.py
from django.urls import path

from requisitions.api.views import RequisitionListCreateAPIView


urlpatterns = [
    path(
        "",
        RequisitionListCreateAPIView.as_view(),
        name="requisition-list"
    )
]

requisitions/urls.py
from django.urls import include, path

from .views import (
    ProjectRequisitionConcatenated,
    RequisitionRegister,
    RequisitionList,
    RequisitionDetail,
    RequisitionThingList,
    RequestedItemList,
    RequisitionPurchaseList,
    ThingRequiredList,
    thing_requisitions_list,
)

app_name = "requisitions"

purchases_patterns = []

things_patterns = [
    path("", RequestedItemList.as_view(), name="requested"),
    path("<int:pk>", ThingRequiredList.as_view(), name="detail")
]

urlpatterns = [
    path("add/", RequisitionRegister.as_view(), name="add"),
    path("", RequisitionList.as_view(), name="list"),
    path("<int:pk>/", RequisitionDetail.as_view(), name="detail"),
    path("lines/", RequisitionThingList.as_view(), name="lines"),
    path(
        "<int:pk>/purchases/",
        RequisitionPurchaseList.as_view(),
        name="purchases"
    ),
    # path("master/", RequestedItemList.as_view(), name="requested-item-list"),
    # Things / Artículos
    # -------------------------------------------------------------------------
    path(
        "things/",
        include(
            (things_patterns, "things"),
            namespace="things"
        )
    ),
    path("test/", ProjectRequisitionConcatenated.as_view(), name="test")
]

requisitions/models.py
import uuid as uuid_lib

from django.contrib.auth import get_user_model
from django.contrib.contenttypes.fields import GenericRelation
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from authorizations.models import Authorization
from projects.models import Project
from sunqu.behaviors import Timestampable
from sunqu.utils import codify
from things.models import Thing
from universal.models import Currency, UnitOfMeasurement

User = get_user_model()


class Requisition(Timestampable):
    # Prioridad
    PRIORITY_URGENT = "ug"  # urgente
    PRIORITY_HIGH = "hi"  # alta
    PRIORITY_MEDIUM = "md"  # media
    PRIORITY_LOW = "lw"  # baja
    PRIORITY_CHOICES = (
        (PRIORITY_URGENT, _("urgent")),
        (PRIORITY_HIGH, _("high")),
        (PRIORITY_MEDIUM, _("medium")),
        (PRIORITY_LOW, _("low")),
    )

    # Estado
    STATE_CREATED = "cr"  # creado
    STATE_OPENED = "op"  # abierto
    STATE_CLOSED = "cl"  # cerrado
    STATE_CANCELED = "cn"  # cancelado
    STATE_CHOICES = (
        (STATE_CREATED, _("created")),
        (STATE_OPENED, _("opened")),
        (STATE_CLOSED, _("closed")),
        (STATE_CANCELED, _("canceled")),
    )
    # uuid
    uuid = models.UUIDField(
        db_index=True,
        default=uuid_lib.uuid4,
        editable=False
    )
    # Código de requerimiento
    code = models.PositiveIntegerField(
        _("code"),
        blank=True,
        unique_for_year="created_at"
    )
    # Proyecto
    project = models.ForeignKey(
        Project,
        on_delete=models.PROTECT,
        related_name="requisitions",
        verbose_name=_("project")
    )
    # Solicitante
    applicant = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name="requisitions",
        verbose_name=_("applicant")
    )
    # Prioridad
    priority = models.CharField(
        _("priority"),
        choices=PRIORITY_CHOICES,
        default=PRIORITY_MEDIUM,
        max_length=2
    )
    # Requerido para <fecha>
    requested_date = models.DateField(
        _("requested date"),
        blank=True,
        null=True
    )
    # Programado para <fecha>
    scheduled_date = models.DateField(
        _("scheduled date"),
        blank=True,
        null=True
    )
    # Atendido el <fecha>
    attention_date = models.DateTimeField(
        _("attention date"),
        blank=True,
        null=True
    )
    # Estado de atención
    state = models.CharField(
        _("state"),
        choices=STATE_CHOICES,
        default=STATE_CREATED,
        max_length=2
    )
    # Razón de anulación
    cancel_reason = models.TextField(
        _("cancel reason"),
        blank=True,
        default=""
    )
    # Autorizaciones
    authorizations = GenericRelation(Authorization)

    class Meta:
        verbose_name = _("requisition")
        verbose_name_plural = _("requisitions")

    def __str__(self):
        str_code = codify(self.code, 5)
        str_year = self.created_at.strftime("%y")
        return f"{str_code}-{str_year}"

    def get_absolute_url(self):
        return reverse("requisitions:detail", kwargs={"pk": self.pk})


class RequisitionThing(models.Model):
    # Requerimiento
    requisition = models.ForeignKey(
        Requisition,
        on_delete=models.CASCADE,
        related_name="things"
    )
    # Artículo
    thing = models.ForeignKey(
        Thing,
        on_delete=models.PROTECT,
        related_name="requisitions",
        verbose_name=_("thing")
    )
    # Demanda / Cantidad
    demand = models.FloatField(_("demand"), default=0.00)
    # Unidad de medida
    uom = models.ForeignKey(
        UnitOfMeasurement,
        on_delete=models.PROTECT,
        verbose_name=_("unit of measurement")
    )
    # Demanda base
    # <Demanda> convertida a la unidad de medida base del artículo.
    # Ex 1: 1.5 Km -> 1500 m
    # Ex 2: 5 doc -> 60 und
    base_demand = models.FloatField(_("base demand"), default=0.00)
    # En reserva (cantidad)
    reserved = models.FloatField(_("reserved"), default=0.00)
    # Atendido (cantidad)
    done = models.FloatField(_("done"), default=0.00)
    # ¿Es permanente?
    is_permanent = models.BooleanField(
        _("permanent"),
        default=True
    )
    # Requerido desde...
    requested_from = models.DateField(
        _("requested from"), blank=True, null=True)
    # Requerido hasta...
    requested_until = models.DateField(
        _("requested until"), blank=True, null=True)

    class Meta:
        verbose_name = _("requisition detail")
        verbose_name_plural = _("requisition details")

    def __str__(self):
        return f"{self.thing}"

    def save(self, *args, **kwargs):
        self.base_demand = self.demand * self.uom.numerical_value
        super().save(*args, **kwargs)


# class Cash(Timestampable, models.Model):
#     DELIVERY_REFERENCE_CASH = "ca"
#     DELIVERY_REFERENCE_CHECK = "ch"
#     DELIVERY_REFERENCE_DEPOSIT = "dp"
#     DELIVERY_REFERENCE_TRANSFER = "tr"
#     DELIVERY_REFERENCE_CHOICES = (
#         (DELIVERY_REFERENCE_CASH, _("cash")),  # efectivo
#         (DELIVERY_REFERENCE_CHECK, _("check")),  # cheque
#         (DELIVERY_REFERENCE_DEPOSIT, _("deposit")),  # depósito
#         (DELIVERY_REFERENCE_TRANSFER, _("transfer")),  # transferencia
#     )
#     # Código de requerimiento de efectivo
#     code = models.PositiveIntegerField(
#         _("code"),
#         unique_for_year="created_at"
#     )
#     # Solicitante
#     applicant = models.ForeignKey(
#         User,
#         on_delete=models.CASCADE,
#         related_name="cash_requisitions",
#         verbose_name=_("applicant")
#     )
#     # Proyecto
#     project = models.ForeignKey(
#         Project,
#         on_delete=models.CASCADE,
#         related_name="cash_requests",
#         verbose_name=_("project")
#     )
#     # Moneda
#     currency = models.ForeignKey(
#         Currency,
#         on_delete=models.PROTECT,
#         verbose_name=_("currency")
#     )
#     # Referencia de entrega
#     delivery_reference = models.CharField(
#         _("delivery reference"),
#         choices=DELIVERY_REFERENCE_CHOICES,
#         default=DELIVERY_REFERENCE_CASH,
#         max_length=2
#     )
#     # Observaciones
#     observation = models.TextField(
#         _("observation"),
#         blank=True,
#         default="",
#         help_text=_("Observation, sustentation")
#     )
#     # Monto total
#     amount_total = models.DecimalField(
#         _("total amount"),
#         decimal_places=3,
#         default=Decimal("0.000"),
#         max_digits=13
#     )
#     # URL Comprobante de desembolso
#     disbursement_voucher = models.URLField(
#         _("disbursement voucher"), blank=True, default="")
#     # Estado de atención
#     # state = models.CharField(
#          _("state"), choices=STATE_CHOICES, max_length=2)
#     # Autorizaciones
#     authorizations = GenericRelation(Authorization)
#
#     class Meta:
#         verbose_name = _("cash requisition")
#         verbose_name_plural = _("cash requisitions")
#
#     def __str__(self):
#         from sunqu.utils import codify
#         code_string = codify(self.code, 5)
#         return f"{code_string}-{self.created_at.year}"

requisitions/forms.py
from django import forms
from django.utils.translation import gettext as _

from .models import Requisition


class RequisitionForm(forms.ModelForm):
    code = forms.IntegerField(
        disabled=True,
        label=_("Code"),
        required=False,
    )

    class Meta:
        model = Requisition
        fields = (
            "code",
            "project",
            "priority",
            "requested_date",
            "scheduled_date",
            "state",
            "attention_date",
        )

requisitions/api/views.py
from rest_framework import generics
from rest_framework import permissions

from requisitions.models import Requisition
from requisitions.api.serializers import (
    RequisitionListSerializer,
    RequisitionDetailSerializer
)


class RequisitionListCreateAPIView(generics.ListCreateAPIView):

    queryset = Requisition.objects.all()
    serializer_class = RequisitionListSerializer
    # permission_classes = [permissions.IsAuthenticated]

    def perform_create(self, serializer):
        print(self.request.data)
        applicant = self.request.user
        serializer.save(applicant=applicant)

requisitions/views.py
from functools import reduce
from operator import or_

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import F, Q, Sum
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from .models import Requisition, RequisitionThing
from projects.models import Project
# from purchases.models import Purchase
from things.models import Thing


# Registrar requerimientos
class RequisitionRegister(CreateView):
    model = Requisition


# Lista de requerimientos
class RequisitionList(ListView):
    model = Requisition

    def get_queryset(self):
        queryset = Requisition.objects.select_related(
            "applicant",
            "applicant__profile",
            "project"
        )
        return queryset


class RequisitionThingList(ListView):
    template_name = "requisitions/requisition_item_list.html"

    def get_queryset(self):
        self.queryset = RequisitionThing.objects.annotate(
            pending=F("demand")-F("done")
        ).exclude(
            pending=0
        ).select_related(
            "requisition",
            "requisition__project",
            "thing",
            "thing__default_uom",
        ).order_by("thing")
        return super().get_queryset()


# Detalle de requerimiento
class RequisitionDetail(DetailView):
    model = Requisition

    def get_queryset(self):
        new_queryset = Requisition.objects.select_related("project")
        return new_queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["items"] = self.object.things.all()
        context["purchase_list"] = self.object.orders.all()
        return context


class RequestedItemList(ListView):
    template_name = "requisitions/requested_item_list.html"

    def get_queryset(self):
        self.queryset = RequisitionThing.objects.values(
            "thing",
            "thing__description",
            "thing__default_uom__abbreviation"
        ).annotate(
            qty_pending=Sum(F("base_demand")-F("done"))
        ).filter(qty_pending__gt=0).order_by("thing__description")
        return self.queryset


# Lista de Compras relacionadas al Requerimiento
class RequisitionPurchaseList(ListView):
    template_name = "requisitions/requisition_purchase_list.html"

    def get_queryset(self):
        self.requisition = get_object_or_404(
            Requisition, pk=self.kwargs.get("pk"))
        self.queryset = Purchase.objects.filter(requisition=self.requisition)
        return super().get_queryset()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["object"] = self.requisition
        return context


# -----------------------------------------------------------------------------
# Things:Required
# -----------------------------------------------------------------------------
class ThingRequiredList(ListView):
    """Vista para lista de artículos requeridos"""
    template_name = "requisitions/requisition_thing.html"

    def get_queryset(self):
        thing = get_object_or_404(Thing, pk=self.kwargs.get("pk"))
        self.queryset = thing.required.select_related("requisition")
        return self.queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["thing"] = get_object_or_404(
            Thing, pk=self.kwargs.get("pk")
        )
        context["requisition_detail_list"] = self.get_queryset()
        return context


def thing_requisitions_list(request, thing_pk):
    thing = Thing.objects.get(pk=thing_pk)
    requisition_detail_list = thing.requisitiondetail_set.select_related(
        "requisition"
    )
    context = {
        "thing": thing,
        "requisition_detail_list": requisition_detail_list
    }
    return render(request, "requisitions/requisition_thing.html", context)


class ProjectRequisitionConcatenated(ListView):
    template_name = "requisitions/project_requisition_concatenated.html"

    def get_queryset(self):
        qs = self.request.GET.get("q", None)
        if qs is None or qs == "":
            return
        qs_arr = qs.split(" ")
        print(qs_arr)
        self.queryset = RequisitionThing.objects.filter(
            reduce(
                or_,
                (Q(requisition__project__alias__iexact=alias) for
                    alias in qs_arr)
            )
        )
        print(self.queryset)
        return super().get_queryset()

requisitions/templates/requisitions/_navigation.html
<li class="nav-item-header"><div class="text-uppercase font-size-xs line-height-xs">Requerimientos</div> <i class="icon-menu" title="Main"></i></li>
<li class="nav-item">
    <a href="{% url 'requisitions:list' %}" class="nav-link ">
        <i class="far fa-list-alt"></i>
        <span>Requerimientos</span>
    </a>
</li>
<li class="nav-item">
    <a href="{% url 'requisitions:lines' %}" class="nav-link ">
        <i class="fas fa-clipboard-list"></i>
        <span>Requerimientos por artículo</span>
    </a>
</li>
<li class="nav-item">
    <a href="{% url 'requisitions:things:requested' %}" class="nav-link">
        <i class="fas fa-th-list"></i>
        <span>Maestro de Artículos Requeridos</span>
    </a>
</li>

requisitions/templates/requisitions/requisition_base.html
{% extends "layouts/sidebar_main.html" %}
{% load static %}


{% comment %}
-------------------------------------------------------------------------------
TITULO DE VENTANA
-------------------------------------------------------------------------------
{% endcomment %}
{% block title %}Limitless | Requerimientos{% endblock title %}


{% comment %}
-------------------------------------------------------------------------------
NAVEGACION LATERAL
-------------------------------------------------------------------------------
{% endcomment %}
{% block navigation %}
{% include "requisitions/_navigation.html" %}
{% endblock navigation %}


{% comment %}
-------------------------------------------------------------------------------
TITULO DE PAGINA
-------------------------------------------------------------------------------
{% endcomment %}
{% block page_icon %}<i class="far fa-list-alt mr-2"></i>{% endblock page_icon %}
{% block page_title %}Requerimientos{% endblock page_title %}


{% comment %}
-------------------------------------------------------------------------------
BREADCRUMBS
-------------------------------------------------------------------------------
{% endcomment %}
{% block breadcrumb %}
    <a href="#" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Inicio</a>
    <a href="{% url 'requisitions:list' %}" class="breadcrumb-item">Requerimientos</a>
{% endblock breadcrumb %}

requisitions/templates/requisitions/requisition_base_dual.html
{% extends "layouts/sidebar_content_right.html" %}
{% load static %}


{% block title %}Limitless | Requerimientos{% endblock title %}


{% block navigation %}
{% include "requisitions/_navigation.html" %}
{% endblock navigation %}


{% block page_icon %}<i class="icon-files-empty2 mr-2"></i>{% endblock page_icon %}
{% block page_title %}Requerimientos{% endblock page_title %}


{% block breadcrumb %}
    <a href="#" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Inicio</a>
    <a href="{% url 'requisitions:list' %}" class="breadcrumb-item">Requerimientos</a>
{% endblock breadcrumb %}
{% block breadcrumb_elements %}
<div class="header-elements d-none">
    <div class="breadcrumb justify-content-center">
        <a href="#" class="breadcrumb-elements-item dropdown-toggle" data-toggle="dropdown">
            Filtrar
        </a>

        <div class="dropdown-menu dropdown-menu-right">
            <a href="?state=PD" class="dropdown-item"><i class="icon-user-lock"></i> Pendientes</a>
            <a href="?state=IP" class="dropdown-item"><i class="icon-statistics"></i> En Progreso</a>
            <a href="?state=DN" class="dropdown-item"><i class="icon-statistics"></i> Atendidos</a>
            <a href="?state=CN" class="dropdown-item"><i class="icon-accessibility"></i> Anulados</a>
            <div class="dropdown-divider"></div>
            <a href="{% url 'requisitions:list' %}" class="dropdown-item"><i class="icon-gear"></i> Todos</a>
        </div>
    </div>
</div>
{% endblock breadcrumb_elements %}

requisitions/templates/requisitions/requisition_item_list.html
{% extends "requisitions/requisition_base.html" %}
{% load static %}


{% block before_app_js %}
<script src="{% static 'js/plugins/tables/datatables/datatables.min.js' %}"></script>
<script src="{% static 'js/plugins/tables/datatables/extensions/responsive.min.js' %}"></script>
<script src="{% static 'js/plugins/forms/selects/select2.min.js' %}"></script>
{% endblock before_app_js %}
{% block after_app_js %}
<script src="{% static 'js/config/datatables/datatable_responsive.js' %}"></script>
<script src="{% static 'requisitions/js/requisition_item_list.js' %}"></script>
{% endblock after_app_js %}


{% comment %}
-------------------------------------------------------------------------------
TITULO SECUNDARIO
-------------------------------------------------------------------------------
{% endcomment %}
{% block page_secondary_title %}<span class="font-weight-light text-grey-600"> / Disgregado</span>{% endblock %}


{% comment %}
-------------------------------------------------------------------------------
SUBTITULO DE PAGINA
-------------------------------------------------------------------------------
{% endcomment %}
{% block page_subtitle %}Lista disgregada de artículos requeridos{% endblock page_subtitle %}
{% block header_elements %}{% endblock header_elements %}


{% comment %}
-------------------------------------------------------------------------------
BREADCRUMB
-------------------------------------------------------------------------------
{% endcomment %}


{% comment %}
-------------------------------------------------------------------------------
CONTENT
-------------------------------------------------------------------------------
{% endcomment %}
{% block content %}
<div class="card">
    <div class="card-header bg-light header-elements-inline">
        <h5 class="card-title">Artículos Requeridos</h5>
        <div class="header-elements">
            <div class="list-icons">
                <a class="list-icons-item" data-action="reload"></a>
            </div>
        </div>
    </div>
    <table class="table datatable-responsive">
        <thead>
            <tr>
                <td></td>
                <td>Nro. Req.</td>
                <td>Cliente</td>
                <td>Descripción</td>
                <td>Demanda</td>
                <td>Pendiente</td>
                <td>U.M.</td>
            </tr>
        </thead>
        <tbody>
            {% for line in object_list %}
            <tr>
                <td></td>
                <td><a href="{% url 'requisitions:detail' line.requisition.pk %}">#{{ line.requisition }}</a></td>
                <td><a href="{% url 'projects:detail' line.requisition.project.pk %}">{{ line.requisition.project }}</a></td>
                <td>{{ line.thing }}</td>
                <td>{{ line.base_demand }}</td>
                <td>{{ line.pending }}</td>
                <td>{{ line.thing.default_uom.abbreviation }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}


{% comment %}
-------------------------------------------------------------------------------
FOOTER
-------------------------------------------------------------------------------
{% endcomment %}

requisitions/templates/requisitions/requisition_list.html
{% extends 'requisitions/requisition_base.html' %}
{% load static tz %}


{% comment %}
-------------------------------------------------------------------------------
JS Files
-------------------------------------------------------------------------------
{% endcomment %}
{% block before_app_js %}
<script src="{% static 'js/plugins/tables/datatables/datatables.min.js' %}"></script>
<script src="{% static 'js/plugins/tables/datatables/extensions/responsive.min.js' %}"></script>
<script src="{% static 'js/plugins/forms/selects/select2.min.js' %}"></script>
{% endblock before_app_js %}
{% block after_app_js %}
<script src="{% static 'js/config/datatables/datatable_responsive.js' %}"></script>
<script src="{% static 'requisitions/js/requisition_list.js' %}"></script>
{% endblock after_app_js %}



{% comment %}
-------------------------------------------------------------------------------
TITULO SECUNDARIO
-------------------------------------------------------------------------------
{% endcomment %}
{% block page_secondary_title %}<span class="font-weight-light text-grey-600"> / Lista</span>{% endblock %}


{% comment %}
-------------------------------------------------------------------------------
SUBTITULO DE PAGINA
-------------------------------------------------------------------------------
{% endcomment %}
{% block page_subtitle %}Lista de requerimientos{% endblock page_subtitle %}
{% block header_elements %}{% endblock header_elements %}


{% comment %}
-------------------------------------------------------------------------------
BREADCRUMB
-------------------------------------------------------------------------------
{% endcomment %}
{% block breadcrumb %}
    {{ block.super }}
    <span class="breadcrumb-item active">Lista</span>
{% endblock breadcrumb %}
{% block breadcrumb_elements %}
<div class="header-elements d-none">
    <div class="breadcrumb justify-content-center">
        <a href="#" class="breadcrumb-elements-item dropdown-toggle" data-toggle="dropdown">
            Filtrar
        </a>

        <div class="dropdown-menu dropdown-menu-right">
            <a href="?state=PD" class="dropdown-item"><i class="icon-user-lock"></i> Pendientes</a>
            <a href="?state=IP" class="dropdown-item"><i class="icon-statistics"></i> En Progreso</a>
            <a href="?state=DN" class="dropdown-item"><i class="icon-statistics"></i> Atendidos</a>
            <a href="?state=CN" class="dropdown-item"><i class="icon-accessibility"></i> Anulados</a>
            <div class="dropdown-divider"></div>
            <a href="{% url 'requisitions:list' %}" class="dropdown-item"><i class="icon-gear"></i> Todos</a>
        </div>
    </div>
</div>
{% endblock breadcrumb_elements %}


{% comment %}
-------------------------------------------------------------------------------
CONTENT
-------------------------------------------------------------------------------
{% endcomment %}
{% block content %}
<div class="card">
    <div class="card-header bg-light header-elements-inline">
        <h5 class="card-title">Lista de Requerimientos</h5>
        <div class="header-elements">
            <div class="list-icons">
                <a target="_blank" href="{% url 'admin:requisitions_requisition_add' %}" class="btn btn-sm btn-light ml-3"><i class="icon-database-add mr-2"></i> Nueva</a>
            </div>
        </div>
    </div>

    <table class="table datatable-responsive">
        <thead>
            <tr>
                <th></th>
                <th>#</th>
                <th class="text-nowrap">Vencimiento</th>
                <th class="text-nowrap">Proyecto</th>
                <th class="text-nowrap">Solicitante</th>
                <th>Prioridad</th>
                <th>Registro</th>
                <th>Estado</th>
            </tr>
        </thead>
        <tbody>
        {% for requisition in object_list %}
            <tr>
                <td></td>
                <td class="text-nowrap"><a href="{% url "requisitions:detail" requisition.pk %}">{{ requisition }}</a></td>
                <td>{{ requisition.requested_date|date:"Y-m-d" }}</td>
                <td><a href="{% url "projects:detail" requisition.project.pk %}">{{ requisition.project }}</a></td>
                <td><a href="#">{{ requisition.applicant.profile }}</a></td>
                <td class="text-center">
                    {% if requisition.priority == "ug" %}
                        <span class="badge badge-danger">{{ requisition.get_priority_display|title }}</span>
                    {% elif requisition.priority == "hi" %}
                        <span class="badge badge-warning">{{ requisition.get_priority_display|title }}</span>
                    {% elif requisition.priority == "me" %}
                        <span class="badge badge-primary">{{ requisition.get_priority_display|title }}</span>
                    {% else %}
                        <span class="badge badge-secondary">{{ requisition.get_priority_display|title }}</span>
                    {% endif %}
                </td>
                <td>{{ requisition.created_at|date:"Y-m-d H:i:s" }}</td>
                <td>
                    {% if requisition.state == "pd" %}
                        <span class="badge badge-secondary">{{ requisition.get_state_display|title }}</span>
                    {% elif requisition.state == "ip" %}
                        <span class="badge badge-primary">{{ requisition.get_state_display|title }}</span>
                    {% elif requisition.state == "dn" %}
                        <span class="badge badge-success">{{ requisition.get_state_display|title }}</span>
                    {% else %}
                        <span class="badge bg-grey">{{ requisition.get_state_display|title }}</span>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}

        </tbody>
    </table>
</div>
{% endblock content %}


{% comment %}
-------------------------------------------------------------------------------
FOOTER
-------------------------------------------------------------------------------
{% endcomment %}

requisitions/templates/requisitions/requisition_purchase_list.html
{% extends 'requisitions/requisition_base.html' %}


{% block page_subtitle %}Lista de compras vinculadas{% endblock page_subtitle %}
{% block header_elements %}{% endblock header_elements %}


{% block breadcrumb %}
    {{ block.super }}
    <a class="breadcrumb-item" href="{% url 'requisitions:detail' object.pk %}">{{ object }}</a>
    <span class="breadcrumb-item active">Compras</span>
{% endblock breadcrumb %}
{% block breadcrumb_elements %}
{% endblock breadcrumb_elements %}

{% block content %}
<div class="card">
    <div class="card-header bg-light header-elements-inline">
        <h5 class="card-title">Lista de Requerimientos</h5>
        <div class="header-elements">
            <div class="list-icons">
                <a class="list-icons-item" data-action="reload"></a>
            </div>
        </div>
    </div>
    <div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>PROVEEDOR</th>
                <th>TOTAL</th>
                <th>ESTADO</th>
            </tr>
        </thead>
        <tbody>
        {% for purchase in object_list %}
            <tr>
                <td class="text-nowrap"><a href="{% url 'purchases:detail' purchase.pk %}">{{ purchase }}</a></td>
                <td>{{ purchase.vendor }}</td>
                <td class="text-nowrap">{{ purchase.currency.symbol }} {{ purchase.amount_total|floatformat:2 }}</td>
                <td>{{ purchase.get_state_display }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    </div>
</div>
{% endblock content %}